name: MovingStructures
author: TJPlaysNow
main: com.pzg.www.movingstructure.main.PluginMain
version: 1.0
description: Will make structures move!!
commands:
  createStructure:
    description: Start creating your custom structure.
  stopEditing:
    description: Stop creating your custom structure.